### ISSUE TITLE
Type generation adds string to union type in every case for internal stories

### ISSUE THREAD

**Issue by mledl** [storyblok/storyblok-cli#101]
**Current behavior:**
Having a block that specifies a field of a type that allows for restricting allowed values by content type (e.g. multi-option, single-option). Running the `generate-typescript-typedefs` command to generate types from such story will always create union type of `ISbStoryData<T>` when content type restriction was configured.  However, the type generator always adds `string` to the union type which does not make much sense to me.
Why does the union needs `string`  in it?

**Expected behavior:**
I would expect to only get a union of `ISbStoryData<T>` generated without adding `string` to the union type.

**Steps to reproduce:**
Create a story with a field of type single-option of multi-option and restrict the content type to some existing block type. Generating typescript types using `generate-typescript-typedefs` command will generate an union type that adds `string` to it.

**Related code:**
https://github.com/storyblok/storyblok-cli/blob/65b31e489c5cd0a8e96be1d6f90c6d6d798c1c54/src/utils/typescript/generateTypesFromJSONSchema.ts#L343-L352

**Other information:**

**Comment by mledl** [comment]
I suppose it can be a string since unresolved stories will just return the reference which can be used to fetch it, right?

**Comment by Edo-San** [comment]
> I suppose it can be a string since unresolved stories will just return the reference which can be used to fetch it, right?

Hey @mledl this is exactly the reason why we are adding `string` to that type 😊 
What I usually do in such cases is to cast the type when I am sure I am resolving relations, like
```js
const foos = blok.foos as ISbStoryData<Foo>[]; // to rule out the string
```

There are some edge cases you need to be aware tho, such as:
- with localized entries (i.e. if you ask for a localized entry that is referencing other stories, and those stories do not have the same localized entry, that story won't be resolved unless you provide the `fallback_lang` param [to the API call](https://www.storyblok.com/docs/api/content-delivery/v2/stories/retrieve-a-single-story)
- with unpublished entries (if you are using a `Public` token - which only fetches published content - and you try to fetch a story that is referencing an unpublished story, that won't be resolved)

This is why the `string` is necessary in terms of Typescript support.

**Comment by mledl** [comment]
Thanks for the response @Edo-San. That totally makes sense. I was just curious if there is a better approach than casting, but I suppose there is not since type generation cannot know about our specific API calls agains Storyblok.

I think we can also work around this by fully resolving the nested object using two or more http calls s.t. the full object is resolved since we need to parse the data anyways.

**Comment by Edo-San** [comment]
That's perfectly fine 👌 
As you said, at the end of the day you want to make sure you have the data you're expecting, so you probably want to set up a fallback to retrieve those data regardless of the potential "issues" that are causing those stories not to be resolved.

For instance, you might want to check if that value is a string, and if it is, perform another call to get the related story.

**Comment by Edo-San** [comment]
Closing as this is "solved". Thank you for raising the flag @mledl!
