### ISSUE TITLE
Error when running `storyblok pull-components` with valid SPACE_ID and token.

### ISSUE THREAD

**Issue by mllustosa** [storyblok/storyblok-cli#107]
**Current behavior:**
On the current version (3.32.3), running `storyblok pull-components --space SPACE_ID` is failing:

**Error Output**
```
- Executing pull-components task
X An error ocurred in pull-components task when load components data
X An error occurred when executing the pull-components task: Error: Error: TypeError: e.headers.entries is not a function
```

**Expected behavior:**
Script should create the components.SPACE_ID.json file.

**Steps to reproduce:**
1. Run `storyblok login` and log in to your account.
2. Run `storyblok pull-components --space SPACE_ID` with the current version (3.32.3) and it should fail.

**Other information:**
Running the exact same command, but pointing to version 3.28.1 works fine: 
`bunx storyblok@3.28.1 pull-components --space SPACE_ID`

**Comment by tstikvoort** [comment]
+1, am running into the same issue with NPM

**Comment by Benzou65** [comment]
+1,  same problem here with 3.32.3 and yarn

```
- Executing pull-components task
X An error ocurred in pull-components task when load components data
X An error occurred when executing the pull-components task: Error: Error: TypeError: e.headers.entries is not a function
```

**Comment by philipp-bender** [comment]
+1 

I also tried version 3.31.1 and 3.30.0 without any success.
Version 3.25.3 seems to work for me.

**Comment by thatzacdavis** [comment]
+1 `3.28.1` does seem to work however

**Comment by mtdvlpr** [comment]
+1

**Comment by kev2480** [comment]
+1

**Comment by rasmusbe** [comment]
Version 3.29 of storyblok-cli did some major rewrites, including an upgrade of storyblok-js-client without any mentions about it in changelog. 👏

**Comment by ademarCardoso** [comment]
Thanks for reporting the issue guys, i will check this now

**Comment by alvarosabu** [comment]
Hi everyone, thanks for raising this and for the information available on the issue. We are currently investigating where this error comes from. 

I will keep you updated.

**Comment by alvarosabu** [comment]
@mllustosa  Potential fix https://github.com/storyblok/storyblok-js-client/pull/852, once is merged I will release a new patch for the CLI that hopefully will solve this issue.

**Comment by thatzacdavis** [comment]
thanks @alvarosabu!

**Comment by alvarosabu** [comment]
@thatzacdavis @mllustosa could you please try out the latest path `v3.33.1` and confirm for me if the error is gone please? 

Thank you 🙏🏻

**Comment by thatzacdavis** [comment]
@alvarosabu I've confirmed this new version is working for me. Thanks for the quick turnaround!

**Comment by mtdvlpr** [comment]
@alvarosabu works for me, thanks!

**Comment by mllustosa** [comment]
@alvarosabu Thanks for the quick reaction there, I confirm it is working as expected now also from my side. All the best!

**Comment by Benzou65** [comment]
@alvarosabu Thanks everyone for the fix. Have a great day.
