### ISSUE TITLE
The `AssetStoryblok` type is missing properties

### ISSUE THREAD

**Issue by ryami333** [storyblok/storyblok-cli#113]
```json
{
  "id": 16807114,
  "alt": "",
  "name": "",
  "focus": "",
  "title": "",
  "source": "",
  "filename": "https://a.storyblok.com/f/foo/bar.jpg",
  "copyright": "",
  "fieldtype": "asset",
  "meta_data": {},
  "is_private": false,
  "is_external_url": false
}
```
This is an example of a real JSON payload that was returned by the Storyblok API for an "asset" field. As you can see, it does not overlap entirely with the `AssetStoryblok` type generated by `generate-sb-types`:

```ts
export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
}
```

As you can see, the payload contains the following additional fields: `is_external_url`, `is_private`, `source`, `fieldtype` and `meta_data`.

**Comment by Edo-San** [comment]
Hi @ryami333 thanks for reporting this inconsistency, much appreciated!
I have filed a PR #122 to fix some of the types for blok fields, including the `Asset` and `Multiasset` fields.
