### ISSUE TITLE
The returned properties of `MultilinkStoryblok` do not match generated type, and should be nullable.

### ISSUE THREAD

**Issue by Joobs** [storyblok/storyblok-cli#115]
Similar to these issues [112](https://github.com/storyblok/storyblok-cli/issues/112) and [113](https://github.com/storyblok/storyblok-cli/issues/113), The type of `MultilinkStoryblok` (generated by `generate-sb-types`) does not match the JSON data returned by the API.

```
export type MultilinkStoryblok =
  | {
      id?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "story";
      target?: "_self" | "_blank";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {};
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {};
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: unknown[];
        default_full_slug?: null | string;
        translated_slugs?: null | unknown[];
      };
    }
  | {
      url?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "asset" | "url";
      target?: "_self" | "_blank";
    }
  | {
      email?: string;
      linktype?: "email";
      target?: "_self" | "_blank";
    };
```

The returned JSON for a link contain additional properties. I've commented out the properties in question

```
// STORY LINK:

{
  id: "123456",
  // url: "",
  linktype: "story",
  // fieldtype: "multilink",
  cached_url: "/test",
  // prep: true,
  story: {
    name: "Example Title",
    id: 123456,
    uuid: "123456",
    slug: "test",
    // url: "test",
    full_slug: "test",
    // _stopResolving: true
  },
};


// EMPTY STORY LINK

{
	id: "",
	// url: "",
	linktype: "story",
	// fieldtype: "multilink",
	cached_url: "",
	// prep: true
};

```

```
// URL LINK:

{
  // id: "",
  url: "/a-test-url",
  linktype: "url",
  // fieldtype: "multilink",
  cached_url: "/a-test-url",
};


// EMPTY URL LINK:

{
  // id: "",
  url: "",
  linktype: "url",
  // fieldtype: "multilink",
  cached_url: "",
};

```

And similar to the `AssetStoryBlok` issues (mentioned earlier), why does does an blank link field return an object, and not `null`/`undefined`? To identify a blank field I have to check the value of the `linkfield` and then based on that check if either the `url` or `id` is blank (depending on if it's a link to a URL or a Story).

Unrelated to this ticket, the Rich Text fields also return an empty object, and requires additional checks to discover if it's blank.

**Comment by Edo-San** [comment]
Hi @Joobs thank you for reporting these inconsistencies and for taking the time to file a detailed comparison. Much appreciated!
I have filed a PR #122 that should fix this 🙏 

As for the question related to the `Asset` field type - which is returning a full object instead of a `null` - that's because of backward compatibility reasons. But you have a point, indeed.
What if we provided a 1st-party way to check those empty values? Something like an `isAssetEmpty(asset)` function - which is nothing short of what you probably already did - exported by our JS libraries? Do you think you would use it and/or do you think it would improve your developer experience?

**Comment by ghost** [comment]
> As for the question related to the `Asset` field type - which is returning a full object instead of a `null` - that's because of backward compatibility reasons. But you have a point, indeed. What if we provided a 1st-party way to check those empty values? Something like an `isAssetEmpty(asset)` function - which is nothing short of what you probably already did - exported by our JS libraries? Do you think you would use it and/or do you think it would improve your developer experience?

Hello, I would much appreciate something like that!! Because the type checking is a bit annyoing with the new PR. Could you post how you would implement that in a clean way? I would just copy it for the time being, but it would be good to have in the future.
