### ISSUE TITLE
CLI doesn't have documented command - generate-typescript-typedefs

### ISSUE THREAD

**Issue by dogfrogfog** [storyblok/storyblok-cli#119]
**Current behavior:**
after executing `storyblok generate-typescript-typedefs` command i see error message
`error: unknown command 'generate-typescript-typedefs'. See 'storyblok --help'.`

**Expected behavior:**
working typegen command, as documented https://github.com/storyblok/storyblok-cli?tab=readme-ov-file#generate-typescript-typedefs and on the website https://www.storyblok.com/faq/how-can-i-utilize-typescript-in-my-storyblok-project

**Steps to reproduce:**
run `storyblok generate-typescript-typedefs` with or without params

https://github.com/user-attachments/assets/0154da26-a765-41e8-9bde-11266872af5c

**Comment by dogfrogfog** [comment]
works now

**Comment by dogfrogfog** [comment]
grats

**Comment by alvarosabu** [comment]
@dogfrogfog thanks for the confirmation, I will close it now, feel free to re-open if you find anything.
