### ISSUE TITLE
Storyblok cli pull components

### ISSUE THREAD

**Issue by dev-me-in** [storyblok/storyblok-cli#15]
Is your feature request related to a problem? Please describe.

I have installed storyblok cli globally. After that in my existing create react app project , I was trying pull my components from storyblok CMS. I’m getting 401error and cannot download the components into my project.

Node version - 10.x
 storyblok pull-components --space=123455

**Comment by ademarCardoso** [comment]
Sorry for the delay in responding, friend, and thanks for opening this issue.

The `401` error is an authorization error, in the current tests the pull components command is working correctly, a tip that works is:
Log out of cli `storyblok logout`
and then login `storyblok login`and try to run the command again `storyblok pull-components --space YOUR_SPACE_ID`

I will close the issue as I believe everything is working fine now and for the time it took us to respond, so my apologies friend, if you still have a problem, we may reopen the issue or open a new one.
