### ISSUE TITLE
Sync don't sync and ask for project name

### ISSUE THREAD

**Issue by pablonunn** [storyblok/storyblok-cli#16]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ X] *Other:* 

**Current behavior:**
The CLI ask for project name "How should your Project be named?"

**Expected behavior:**
Sync source and target spaces

**Steps to reproduce:**
Just run the command like it is explained in the documentation.
storyblok sync --type components --source 00001 --target 00002

**Comment by ademarCardoso** [comment]
Hello my friend, I apologize for the delay in responding to you.

I didn't understand the issue very well. The message you wrote is from the `select` command, this command is designed for you to create a project from scratch with some ready-made settings.

In **_Steps to reproduce_**: you say about the `sync` command, the `sync` command has the function of synchronizing folders, components, datasources between two already existing spaces.

I don't understand exactly what you need in this issue, could you give me more details and information? Thanks in advance

cc: @pablonunez-dev

**Comment by ademarCardoso** [comment]
Due to user inactivity, I closed this issue, if you have this problem again, please open a new issue or we can reopen this one. Thanks
