### ISSUE TITLE
Upgrade to js-client version 5

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok-cli#45]
**Current behavior:**

Currently the cli is still at version 4. This causes a mismatch in projects that has both a framework (for example nuxt or vue) and the cli.

**Expected behavior:**

I expect all storyblok js modules to be up to date.

**Comment by ademarCardoso** [comment]
Thanks to remember that, i will check this problem next week 😄 .

**Comment by ademarCardoso** [comment]
Added in the version [v3.25.0](https://github.com/storyblok/storyblok-cli/releases/tag/v3.25.0)

**Comment by SebbeJohansson** [comment]
Ey nice job 🥳
