### ISSUE TITLE
Filter in and not_in operations not working

### ISSUE THREAD

**Issue by maartenjongerius** [storyblok/storyblok-cli#54]
**Current behavior:**
I'm currently facing an issue concerning this functionality. The `filter` functionality doesn't seem to work when I want to use the `in` or `not_in` operation.

When I use it in line with the [documentation](https://www.storyblok.com/docs/api/content-delivery/v2#filter-queries/operation-in) , it returns an error `An error occurred when executing the sync task: Error: The number of keys, operations and values must be the same` due to the way the `options` are handled right now.

**Expected behavior:**
I expect the sync cli to be able to handle the `in` and `not_in` filter operations according to the documentation.

**Steps to reproduce:**
See code example below.

**Related code:**

```
storyblok sync --type stories --source 0001 --target 0002 --filter --keys component --operations in --values component1,component2
```

**Other information:**
- storyblok cli version: `3.24.1`
- node version: `v18.13.0`

**Comment by ademarCardoso** [comment]
Hello @maartenjongerius thanks to reporting the problem, for now we removed the feature to sync with filters by performance issues, we area checking the possibility to add this feature again and when we back with this functionality we will look at this issue. But if you need more assistance to sync this values or a way to solve this specific problem ping us in the support chat in the CMS frontend 😄
