### ISSUE TITLE
storyblok sync fails in v3.25.0

### ISSUE THREAD

**Issue by snikidev** [storyblok/storyblok-cli#63]
**Current behavior:**
When running `storyblok sync --type components,datasources,folders --source ... --target ...` script with v3.25.0 every component sync fails
![Screenshot 2023-07-20 at 11 08 02](https://github.com/storyblok/storyblok-cli/assets/10689226/6d813130-0c3e-4fcc-a92d-b507f5ef815c)

**Expected behavior:**
Should be as is with v3.24.2, sync components without errors
![Screenshot 2023-07-20 at 11 08 51](https://github.com/storyblok/storyblok-cli/assets/10689226/7a927982-2f30-4814-b80f-a290e851de02)

**Steps to reproduce:**
1. run the command with `npx storyblok@latest sync --type components,datasources,folders --source {source id} --target {target id}`

**Other information:**
Similar command works fine with `npx storyblok@3.24.2`

**Comment by ademarCardoso** [comment]
Hi @snikidev can you check if the components you are trying to sync already exist in the target space ?

**Comment by snikidev** [comment]
@ademarCardoso they most definitely do. That never stopped the sync before though.

And, as I mentioned, the sync works fine with v3.24. It's something that happened in v3.25 release that introduced this bug.

**Comment by ademarCardoso** [comment]
Thanks to confirm this problem i will take a look on that.

**Comment by ademarCardoso** [comment]
Hello again my friend @snikidev i added some changes and published the version [3.25.2](https://github.com/storyblok/storyblok-cli/releases/tag/v3.25.2), could you check to see if this version it's working ?

**Comment by ademarCardoso** [comment]
I believe the problem is resolved and therefore I will close this issue, if the problem has not been resolved, we open the issue again 😄
