### ISSUE TITLE
Datasources sync fails

### ISSUE THREAD

**Issue by juliavorcakova** [storyblok/storyblok-cli#66]
**Current behavior:**
We have encountered an issue with the synchronization of datasources between two spaces. During the process of syncing, the job fails, and following error message is generated. 
`X Datasource example update failed: Cannot read properties of undefined (reading 'data’)`
Part of the datasources is copied to the target space but some are missing.

**Expected behavior:**

All datasources from source space sync correctly with target space without error.

**Steps to reproduce:**
storyblok sync --type datasources --source 00001 --target 00002

**Other information:**
storyblok-cli version: 3.25.0
From what was observed this behavior occurs for datasources containing more than 25 entries.

**Comment by ademarCardoso** [comment]
Hello @juliavorcakova i merged a fix could you check if it's working now ?

Thanks to reporting the problem 😄 

The version with the fix => [3.25.1](https://github.com/storyblok/storyblok-cli/releases/tag/v3.25.1)

**Comment by juliavorcakova** [comment]
> Hello @juliavorcakova i merged a fix could you check if it's working now ?
> 
> Thanks to reporting the problem 😄
> 
> The version with the fix => [3.25.1](https://github.com/storyblok/storyblok-cli/releases/tag/v3.25.1)

Thank you @ademarCardoso, the issue is fixed now!
