### ISSUE TITLE
Cannot connect to existing space after updating

### ISSUE THREAD

**Issue by JamesCatt** [storyblok/storyblok-cli#70]
**Current behavior:**
After updating storyblok-cli (v3.25.0 --> v3.25.2), and logging in, every `storyblok` command attempts to initialize a new space instead of executing the command in question. For example, running `storyblok pull-components --space [myspaceid]` or even `storyblok --help` or `storyblok --version` all result in the "How should your Project be named?" prompt.

**Expected behavior:**
The entered commands should execute instead of creating a new space.

**Steps to reproduce:**
```
> npm uninstall -g storyblok-cli
> npm install -g storyblok-cli
> storyblok logout
> storyblok login --token [myaccesstoken] --region us
> storyblok --help
```

**Related code:**

```
insert any relevant code here
```

**Other information:**
I've tried entering the name of my existing space at the prompt, but all it does is create a new space with the same name.

**Comment by ademarCardoso** [comment]
Hi @JamesCatt i will take a look on that.

**Comment by ademarCardoso** [comment]
My friend i'm sorry but you need to[ install the CLI with this command](https://github.com/storyblok/storyblok-cli#installation):

```sh
npm install -g storyblok
````

If you install with `npm install -g storyblok-cli` you will get an old version that is no longer supported.

Note: I will deprecate this package that is no longer supported.

cc: @JamesCatt
