### ISSUE TITLE
The generate-typescript-typedefs command throws property.filter_content_type.map is not a function

### ISSUE THREAD

**Issue by pawelgrzybek** [storyblok/storyblok-cli#94]
**Current behavior:**
While running generate-typescript-typedefs command, I am getting the following error.

```
file:///Users/pawelgrzybek/Desktop/sb/node_modules/.pnpm/storyblok@3.30.0/node_modules/storyblok/dist/cli.mjs:3309
        tsType: `(${property.filter_content_type.map((type2) => __privateMethod(this, _getStoryType, getStoryType_fn).call(this, type2)).join(" | ")} | string )${property.type === "options" ? "[]" : ""}`
                                                 ^

TypeError: property.filter_content_type.map is not a function
    at _GenerateTypesFromJSONSchemas.getPropertyTypeAnnotation_fn (file:///Users/pawelgrzybek/Desktop/sb/node_modules/.pnpm/storyblok@3.30.0/node_modules/storyblok/dist/cli.mjs:3309:50)
    at _GenerateTypesFromJSONSchemas.getTypeAnnotationsForComponentProperties_fn (file:///Users/pawelgrzybek/Desktop/sb/node_modules/.pnpm/storyblok@3.30.0/node_modules/storyblok/dist/cli.mjs:3240:103)
    at async _GenerateTypesFromJSONSchemas.generateTSFile (file:///Users/pawelgrzybek/Desktop/sb/node_modules/.pnpm/storyblok@3.30.0/node_modules/storyblok/dist/cli.mjs:3166:50)
    at async Object.generateTypescriptTypedefs (file:///Users/pawelgrzybek/Desktop/sb/node_modules/.pnpm/storyblok@3.30.0/node_modules/storyblok/dist/cli.mjs:3465:12)
```

**Expected behavior:**
To have TS types generated.

**Steps to reproduce:**
Unfortunately I am unable to provide a source file, as it contains structure specific to my company. I am more than happy to share it via private channel. Luckily I managed to narrow the issue down slightly.

https://github.com/storyblok/storyblok-cli/blob/master/src/utils/typescript/generateTypesFromJSONSchema.ts#L347

```ts
    if (property.source === "internal_stories") {
      if (property.filter_content_type) {
        return {
          tsType: `(${property.filter_content_type
//           👇 - property.filter_content_type can also be a string, and this is the case for my schema
            .map((type2) => this.#getStoryType(type2))
            // In this case property.type can be `option` or `options`. In case of `options` the type should be an array
            .join(" | ")} | string )${property.type === "options" ? "[]" : ""}`,
        };
      }
    }
```

**Other information:**

Issue is consistent on Node.js 18 and Node.js 20.

**Comment by bemayr** [comment]
Just stumbled upon exactly the same issue in Node.js 20.
Can fully confirm @pawelgrzybek's analysis as these are the different values for `filter_content_type`:

```
"filter_content_type": "author"         // string
"filter_content_type": ["reference"],   // Array<string>
```
After manually wrapping the plain `string` occurrences inside arrays, the generation works without a problem.

---

## "Solution"
Edit: I have looked into this a bit more and it seems like the pre-generated components when using the Blog template on Storyblok contain these `string`-properties, going through the components with the invalid configuration in Storyblok UI and deleting + re-adding the restricted content types "solves" the issue.
After this `storyblok pull-components` exports the components with array types for the content restrictions, thus preventing the type generation from running into errors.

**Comment by kelenakamura** [comment]
going through the storyblok UI and re-adding restricted content types fixed the string vs arrays issue for us as well!

**Comment by pawelgrzybek** [comment]
I can confirm that I solved my issue by re-saving all blocks that use content filters via UI.

I imagine that a change in the data structure from string to array of strings happened internally over time so plenty of schemas generated in the past contain raw strings. That was the case for me. Since Storyblok internally handle both cases, TS conversion should also transparently convert raw strings into array of strings.

Thanks for good tip @bemayr

**Comment by pawelgrzybek** [comment]
That should do: https://github.com/storyblok/storyblok-cli/pull/103

**Comment by Edo-San** [comment]
Thank you @pawelgrzybek for bringing this up!
You made a pretty accurate depiction of the issue: there has been a change to the exposed schema data structure and from that moment onwards all the `filter_content_type` have been handled as arrays, while in the past they used to be strings.

Thanks for opening a PR to fix this inconsistency and for making Storyblok a better place! 🙏
