### ISSUE TITLE
`run-migration` is broken after ESM migration

### ISSUE THREAD

**Issue by privetkuku** [storyblok/storyblok-cli#95]
**Current behavior:**
- Generate migration. It will produce .js file with `export default` ESM statement
- Run `run-migration`. Error will be thrown, because Node.js didn't expect to see ESM export in `.js` file

**Expected behavior:**
- Migration is executed without error

**Steps to reproduce:**
Steps are described in Current behaviour section.

**Related code:**
Code that broke the functionality - https://github.com/storyblok/storyblok-cli/commit/891af62c7a628286f507299b19128a2193a55550#diff-2c9538c486ae6103ef79ac65657bf841191ae869f4992158328e6739c28e463c

**Other information:**
To fix the issue, you need to generate `.mjs` files, not `.js`. 
Current "fix" for me is to use `--experimental-detect-module` flag, but that's not safe.

**Comment by OFranke** [comment]
I am running into the same issue, but your "fix" using `--experimental-detect-module` doesn't work for me. It just tells me `error: unknown option '--experimental-detect-module'`. Which CLI version did you install @privetkuku ?

**Comment by privetkuku** [comment]
@OFranke, I have `3.30.0` version installed. `'--experimental-detect-module'` was introduced in Node `21.1.0` and you need to pass it to the Node itself, not Storyblok.

I use `pnpm`, for me it looks like this: `NODE_OPTIONS='--experimental-detect-module' pnpm storyblok ...`.

Hope that helps.

**Comment by privetkuku** [comment]
@christianzoppi, can you please into it?

**Comment by alvarosabu** [comment]
Hey there @privetkuku @OFranke I'm currently checking out this issue. 

If I understand correctly, the problem comes when trying to run previously generated CJS versions of the migrations in the newest versions right? I guess it also depends on the Node version of the project if it's using `>18` or not 🤔.

**Comment by privetkuku** [comment]
Hello @alvarosabu, thanks for looking into it!
After version bump back then, even newly created migrations were not able to run due to the described reasons in **Current behavior** section.
I see your fix #116, I think it should do the job🦉
